apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: service-bus-connection-string
    app.kubernetes.io/part-of: ${APP_NAME}
  name: service-bus-connection-string
data:
  data: ${CONNECTION_STRING_BASE64}
